@startuml

' Figure 20

skinparam componentStyle uml2
skinparam ArrowColor Black
skinparam ClassBorderColor Black
skinparam ComponentBorderColor Black
skinparam ObjectBorderColor Black

hide circle
' hide <<Resource>> circle
show <<GeoJSON>> circle




object "<<JSON>>\nidn:LandingPage" as federating_ldp {
   path = "https://idn.ceos.org/"
}



object "<<JSON>>\nidn:Collections" as federating_collections {
   path = "https://idn.ceos.org/collections"
}

federating_ldp ..> federating_collections : "rel="data""

object "<<JSON>>\nfedeo:LandingPage" as federated_ldp {
   path = "https://fedeo.ceos.org"
}

object "<<JSON>>\nfedeo:Collections" as federated_collections {
  path = "https://fedeo.ceos.org/collections"
}

object "<<GeoJSON>>\nfedeo:Search" as federated_search {
   path = "https://fedeo.ceos.org/search"
}

federated_ldp --> federated_collections : "rel="data""
federated_ldp --> federated_search : "rel="search""

federating_ldp --> federating_collections : "rel="search""

federating_ldp .right.> federated_ldp : "rel="child""


object "<<JSON>>\nPROBA_CHRIS_1A:Collection" as PROBA_CHRIS_1A {
      path = "https://fedeo.ceos.org/collections/PROBA_CHRIS_1A"
}

object "<<JSON>>\nPROBA_CHRIS_1A:Collection" as PROBA_CHRIS_1A_federating {
      path = "https://idn.ceos.org/collections/PROBA_CHRIS_1A"
}


object "<<GeoJSON>>\n:Features" as federated_items {
  path = "https://fedeo.ceos.org/collections/\n  PROBA_CHRIS_1A/items"
}

object "<<JSONSchema>>\n:Queryables" as queryables {
  path = "https://fedeo.ceos.org/collections/\n  PROBA_CHRIS_1A/queryables"
}

object "<<JSONSchema>>\n:Queryables" as federated_queryables {
  path = "https://fedeo.ceos.org/queryables"
}

object "<<JSONSchema>>\n:Queryables" as federating_queryables {
  path = "https://idn.ceos.org/queryables"
}

federating_ldp .up.> federating_queryables : "rel="queryables""
federated_ldp .up.> federated_queryables : "rel="queryables""

federated_collections o-down- PROBA_CHRIS_1A

federating_collections o-down- PROBA_CHRIS_1A_federating


PROBA_CHRIS_1A --> federated_items : "rel="items""

PROBA_CHRIS_1A ..> queryables : "rel="queryables""

PROBA_CHRIS_1A_federating ..> queryables : "rel="queryables""

PROBA_CHRIS_1A_federating --> federated_items : "rel="items""

PROBA_CHRIS_1A_federating --> federated_search : "rel="search""





@enduml